---
database_file: "/home/patrick/Dropbox/.timetrap.db"
round_in_seconds: 900
append_notes_delimiter: ""
formatter_search_paths:
- "/home/patrick/.timetrap/formatters"
auto_sheet: dotfiles
auto_sheet_search_paths:
- "/home/patrick/.timetrap/auto_sheets"
default_command: d --ids
auto_checkout: false
require_note: true
note_editor: "vim"
